In [11]:
import pandas as pd

df_origin = pd.read_csv('USFK Holiday Schedule FY 2024 Spreadsheet-(v3-25 Sep 23) w DoDEA (1).csv', index_col=False)
df_origin.head()

,DATE,DAY,HOLIDAY,US,ROK,KATUSA,DOD (US),USFK (LN),CFC (KN),DODEA (US)
0,2-Oct-23,MONDAY,CHUSEOK (ROK)/NATIONAL FOUNDATION BRIDGE DAY,NO,YES,YES,NO,YES,YES,NO
1,3-Oct-23,TUESDAY,NATIONAL FOUNDATION DAY (ROK),NO,YES,NO,NO,YES,YES,NO
2,6-Oct-23,FRIDAY,COLUMBUS DAY (US) TRAINING HOLIDAY,YES,NO,YES,NO,NO,NO,CCRS
3,9-Oct-23,MONDAY,HANGUL (KOREAN LANGUAGE) DAY (ROK),NO,YES,NO,NO,YES,YES,NO
4,9-Oct-23,MONDAY,COLUMBUS DAY (US),YES,NO,YES,YES,NO,NO,YES

In [12]:
df_origin.to_json('fy24_usfk_holiday.json', orient='records')